# Generated by Django 5.2.15 on 2026-06-07 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=16)),
                ('position', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('paragraph', 'テキスト'), ('heading_1', '見出し1'), ('heading_2', '見出し2'), ('heading_3', '見出し3'), ('to_do', 'ToDo リスト'), ('bulleted_list_item', '箇条書きリスト'), ('numbered_list_item', '番号付きリスト'), ('quote', '引用'), ('divider', '区切り線'), ('code', 'コード')], default='paragraph', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('checked', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['parent', 'is_deleted', 'position'], name='pages_page_parent__173d16_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'position'], name='pages_block_page_id_a93eaa_idx'),
        ),
    ]
