# Generated by Django 5.2.15 on 2026-06-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_search_trgm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='block',
            name='pages_block_page_id_a93eaa_idx',
        ),
        migrations.AddField(
            model_name='block',
            name='collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('paragraph', 'テキスト'), ('heading_1', '見出し1'), ('heading_2', '見出し2'), ('heading_3', '見出し3'), ('to_do', 'ToDo リスト'), ('bulleted_list_item', '箇条書きリスト'), ('numbered_list_item', '番号付きリスト'), ('quote', '引用'), ('divider', '区切り線'), ('code', 'コード'), ('toggle', 'トグル')], default='paragraph', max_length=32),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'parent', 'position'], name='pages_block_page_id_879d96_idx'),
        ),
    ]
