# Generated by Django 5.2.15 on 2026-06-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_block_pages_block_page_id_a93eaa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
