# Generated by Django 5.2.15 on 2026-06-09 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
        ('pages', '0006_pagesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('secret', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='pages.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('event', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '待機中'), ('done', '成功'), ('failed', '失敗')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='exports.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['page', 'is_active'], name='exports_web_page_id_dfde30_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('webhook', 'event_id'), name='unique_delivery_per_event'),
        ),
    ]
