# Generated by Django 5.2.15 on 2026-06-09 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_pagesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database', to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='databases.database')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_row', to='pages.page')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['database', 'position'], name='databases_d_databas_0faea7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertySchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('select', 'select'), ('multi_select', 'multi_select'), ('date', 'date'), ('checkbox', 'checkbox'), ('relation', 'relation')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='databases.database')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['database', 'position'], name='databases_p_databas_b0524a_idx')],
                'constraints': [models.UniqueConstraint(fields=('database', 'key'), name='unique_property_key_per_database')],
            },
        ),
    ]
