# Generated by Django 5.2.15 on 2026-06-09 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_databaserow_values_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='ビュー', max_length=255)),
                ('type', models.CharField(choices=[('table', 'テーブル'), ('board', 'ボード')], default='table', max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('sorts', models.JSONField(blank=True, default=list)),
                ('group_by', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='databases.database')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['database', 'position'], name='databases_d_databas_3c63bd_idx')],
            },
        ),
    ]
